import os
from fpdf import FPDF
from datetime import date

# Ensure the folder exists
UPLOAD_DIR = "admit_letters"
if not os.path.exists(UPLOAD_DIR):
    os.makedirs(UPLOAD_DIR)

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Sairam Group of Institutions', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Creating a Better Future | Excellence in Education', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by Sairam Admission System', 0, 0, 'C')

def generate_admit_letter(student_name, course, ref_id, institution_name, institution_type):
    pdf = PDF()
    pdf.add_page()
    
    # 1. DATE & REF
    pdf.set_font("Arial", size=11)
    pdf.cell(0, 10, f"Date: {date.today().strftime('%B %d, %Y')}", 0, 1, 'R')
    pdf.cell(0, 10, f"Ref No: {ref_id}", 0, 1, 'R')
    pdf.ln(10)

    # 2. SALUTATION (Logic to address Parent vs Student)
    pdf.set_font("Arial", 'B', 12)
    if institution_type == "School":
        pdf.cell(0, 10, f"Dear Parent / Guardian of {student_name},", 0, 1)
    else:
        pdf.cell(0, 10, f"Dear {student_name},", 0, 1)
    pdf.ln(5)

    # 3. DEFINE CONTENT (Initialize variables to prevent errors)
    intro = ""
    docs_intro = ""
    doc_list = []
    signer = ""

    # --- LOGIC BLOCK ---
    if institution_type == "School":
        intro = (
            f"We are delighted to inform you that your child, {student_name}, has been PROVISIONALLY SELECTED "
            f"for admission into {course} at {institution_name} for the academic year 2026-2027.\n\n"
            "This selection is based on the interaction/assessment conducted by our admissions team. "
            "To confirm the seat, please complete the initial fee payment within 7 days."
        )
        docs_intro = "Please submit the following original documents for verification at the school office:"
        doc_list = [
            "1. Original Birth Certificate",
            "2. Vaccination / Immunization Record",
            "3. Transfer Certificate (from previous school, if applicable)",
            "4. EMIS Number Details",
            "5. Recent Passport Size Photos (Child & Parents)",
            "6. Address Proof (Aadhaar/Ration Card)"
        ]
        signer = "Principal"

    elif institution_type == "Medical":
        intro = (
            f"Congratulations! We are pleased to inform you that you have been PROVISIONALLY SELECTED for admission "
            f"into the {course} program at {institution_name} for the academic year 2026-2027.\n\n"
            "Your selection is based on your NEET Score and Medical Fitness. "
            "To confirm your seat, please complete the admission fee payment immediately."
        )
        docs_intro = "Mandatory documents for Medical Admission Verification:"
        doc_list = [
            "1. NEET Score Card & Admit Card (Original)",
            "2. 10th & 12th Marksheets",
            "3. Transfer Certificate & Conduct Certificate",
            "4. Community Certificate",
            "5. Physical Fitness Certificate (from Govt Doctor)",
            "6. Hepatitis B Vaccination Certificate",
            "7. Eligibility Certificate (The TN Dr. M.G.R. Medical University)"
        ]
        signer = "Dean / Medical Director"

    else:
        # Default for Engineering / Polytechnic
        intro = (
            f"Congratulations! We are pleased to inform you that you have been PROVISIONALLY SELECTED for admission "
            f"into the {course} program at {institution_name} for the academic year 2026-2027.\n\n"
            "Your selection is based on your academic merit and eligibility criteria. "
            "To confirm your provisional seat, please complete the semester fee payment within 7 days."
        )
        docs_intro = "Please bring the following original documents for verification during your campus visit:"
        doc_list = [
            "1. 10th Standard Marksheet",
            "2. 12th Standard / HSC Marksheet (or Diploma Cert)",
            "3. Transfer Certificate (TC) & Conduct Certificate",
            "4. Community Certificate (if applicable)",
            "5. Entrance Exam Score Card (if applicable)",
            "6. Recent Passport Size Photographs"
        ]
        signer = "Principal"

    # 4. RENDER BODY
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 7, intro)
    pdf.ln(10)
    
    # 5. RENDER DOC LIST
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 10, docs_intro, 0, 1)
    pdf.set_font("Arial", size=11)
    
    for doc in doc_list:
        pdf.cell(10) # Indent
        pdf.cell(0, 8, doc, 0, 1)
    
    pdf.ln(15)
    
    # 6. CLOSING & SIGNATURE
    pdf.multi_cell(0, 7, "We welcome you to the Sairam family and look forward to a successful academic journey.")
    pdf.ln(20)

    pdf.cell(0, 10, "Sincerely,", 0, 1)
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 10, signer, 0, 1)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, institution_name, 0, 1)

    # 7. SAVE FILE
    filename = f"Admit_Letter_{ref_id}.pdf"
    filepath = os.path.join(UPLOAD_DIR, filename)
    pdf.output(filepath)
    
    return filename